spring.datasource.url=jdbc:postgresql://localhost:5432/driveai
spring.datasource.username=username
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update

jwt.secret=secretkey
jwt.expiration=expiry

minio.endpoint=endpoint
minio.access-key=username
minio.secret-key=password
minio.bucket=bucketname

spring.servlet.multipart.max-file-size=size
spring.servlet.multipart.max-request-size=size

app.file.max-size=maxsize
server.servlet.context-path=/yourapi


